"""initial migration

Revision ID: d2fe9979feb9
Revises: dc9ecf181330
Create Date: 2023-06-03 12:35:04.293275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2fe9979feb9'
down_revision = 'dc9ecf181330'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###
